
services:
  my_server:
    build:
      context: ./Project
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: >
            bash -c "python manage.py makemigrations &&
                     python manage.py migrate &&
                     python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Project:/Project
    ports:
      - 8000:8000
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    depends_on:
      - my_server
  
  celery:
    build: ./Project
    command: celery -A config worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - ./Project:/Project
    depends_on:
      - my_server
      - redis





