# Generated by Django 5.1 on 2024-08-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='cadastral_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
