# Generated by Django 5.1 on 2024-08-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_api', '0003_remove_results_query_remove_query_unique_property_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='query',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
